### ISSUE TITLE
snappy-java is Apache 2.0 licensed but ships GPL code

### ISSUE THREAD

**Issue by jsievers** [xerial/snappy-java#113]
snappy-java is Apache 2.0 licensed,
but it looks like it ships GPL code (contains statically linked libstdc++ governed by license [1])
which according to [2] is not license compatible.

Eclipse.org IP review found this in the context of https://bugs.eclipse.org/bugs/show_bug.cgi?id=461974
(we want to use plexus-archiver https://github.com/codehaus-plexus/plexus-archiver which in turn uses snappy-java). 
Unfortunately as long as this license issue is not solved this renders plexus-archiver (and snappy-java) unusable for our purposes as governed by [EPL license](https://www.eclipse.org/legal/epl-v10.html)  compatibility .

[1] https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html 
[2] http://www.apache.org/licenses/GPL-compatibility.html

**Comment by pwendell** [comment]
This could be an issue for us (Spark) too as well as several of the Apache projects that use Snappy. I think it might be necessary for snappy-java to have a mode where it does dynamic linking rather than embedding the C++ standard library.

**Comment by xerial** [comment]
snappy-java does not distribute a pure libstdc++. See also the discussion in https://lwn.net/Articles/549573/ 

If this explanation is correct, [1]

**Comment by xerial** [comment]
@jsievers 
Please look at this official FAQ: http://www.gnu.org/licenses/gcc-exception-3.1-faq.en.html

> As long as you use an Eligible Compilation Process, then you have permission to take the Target Code that GCC generates and propagate it “under terms of your choice.”

snappy-java just uses GCC (without any modification to GCC itself), so it is under Eligible Compilation Process.

An important point is GPL and GCC Runtime Library Exception does not distinguish linking methods (dynamic and static link):
>  While combining libgcc with GCC-compiled object code is probably the most common way the exception is used, neither the GPL nor the GCC Runtime Library Exception distinguish between static linking, dynamic linking, and other methods for combining code in their conditions. The same permissions are available to you, under the same terms, no matter which method you use.

@pwendell According to this, providing a dynamic-link version does not make much sense. As long as snappy-java does not distribute libstdc++.so itself, it never falls under GPL. 

So the point is whether GCC Runtime Library Exception applies to snappy-java. I believe this applies to snappy-java. 

See also the discussion for a similar case:
 - http://stackoverflow.com/questions/10838807/license-of-runtime-libraries-included-in-gcc

**Comment by jsievers** [comment]
I am forwarding the legal questions to the eclipse.org IP review team as I'm not qualified to answer. Hope they will post here.

**Comment by xerial** [comment]
I think this FAQ tells me enough:  
https://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.license.what

c++ library uses a lot of inline functions and templates, which will be eventually embedded in the compiled objects. So technically speaking there is no difference between statically- and dynamically linked objects in that they contain a part of GPL code. 

This exception is for allowing to use libstdc++ to develop non-GPL products.  On the other hand, if we embed libc.so, it would be GPL since glibc is LGPL, but for c++, for the reason mentioned above there is no way to distinguish GPL and LGPL, that is why such an exception was needed. This is my understandings.

I feel there is no need to wait the third party opinion, since we already get an answer from the official site. 

Let me close this ticket. 

Thanks.
