### ISSUE TITLE
Snappy-java outputstream not compatible with Hadoop

### ISSUE THREAD

**Issue by winston-zillow** [xerial/snappy-java#177]
Please review/resolve https://github.com/xerial/snappy-java/pull/176 if you get a chance. Thanks

**Comment by winston-zillow** [comment]
hi, is there any progress in this? hope to see it released.

**Comment by xerial** [comment]
This will be in snappy-java-1.1.7

**Comment by winston-zillow** [comment]
Thank you for doing this! Can’t wait to upgrade!

**Comment by xerial** [comment]
@winston-zillow During the merge process, I need to modify your commits directory because of some merge conflicts, and your git commit activities in snappy-java repo happened to be erased. Sorry about that.

If you have more time, could you do me a favor to update README.md to mention about the new SnappyHadoopCompatibleOutputStream? 
https://github.com/xerial/snappy-java#compatibility-notes

**Comment by winston-zillow** [comment]
No problem. I just created a PR
