### ISSUE TITLE
FAILED_TO_LOAD_NATIVE_LIBRARY for Solaris 11 Sparc server

### ISSUE THREAD

**Issue by xiyuanHou** [xerial/snappy-java#178]
I have an error while running Apache Spark on Solaris 11 sparc server, error caused by :

org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=SunOS and os.arch=sparcv9

**Comment by evan912** [comment]
It seems current version only support SunOS(solaris) 32-bit  sparc: 
"org/xerial/snappy/native/SunOS/sparc/libsnappyjava.so;osname=sunos;processor=sparc"
But not support for 64-bit sparcv9 system. Please add this support, thanks.

**Comment by xerial** [comment]
@evan912 We don't have portable way to build Solaris library (e.g., using a cross compiler, etc.) If you have a Soralis 11 with 64-bit spark, please build the native library with `make native test` and send a PR.

**Comment by evan912** [comment]
Thanks @xerial , I will try to build with solaris 11 64-bit sparc. Current solution for running Apache Spark is to change to other Compressor in configuration temporarily.

**Comment by amateur-RD** [comment]
@evan912  I have a similar problem,I want to run Apache spark on Linux-sw, error caused by 

org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Linux and os.arch=sw

ok, I would like to ask you, how did you modify it, and what modifications have you made? thanks!

@xerial hi, Do you have some specific implementations or ideas? I want snappy-java to support Linux-sw. thanks!

**Comment by evan912** [comment]
@amateur-RD   You can change setting of spark.io.compression.codec to lzf.  The default setting of Spark is using snappy as compressor, but it not supported some platform.

**Comment by amateur-RD** [comment]
Thank you very much! @evan912 It has been successfully modified and running successfully. thanks!

**Comment by xerial** [comment]
Added pure-java snappy implementation in 1.1.7.6. I think it will support Sparc as well.
